const {test}=require('node:test');const assert=require('node:assert/strict');const React=require('react');const {act}=React;const {createRoot}=require('react-dom/client');const {JSDOM}=require('jsdom');const Module=require('node:module');const path=require('node:path');
function hook(){const file=path.resolve('components/character-vault/use-cloud-vault.js');const out=require('esbuild').buildSync({entryPoints:[file],bundle:true,write:false,platform:'node',format:'cjs',external:['react']});const m=new Module(file,module);m.paths=module.paths;m._compile(out.outputFiles[0].text,file);return m.exports.useCloudVault;}
test('vault consumes flat API records, saves full builds, loads and duplicates',async()=>{
 const dom=new JSDOM('<div id="root"></div>',{url:'https://site.test'});global.window=dom.window;global.document=dom.window.document;global.IS_REACT_ACT_ENVIRONMENT=true;
 window.Clerk={user:{id:'one'},session:{getToken:async()=> 'token'},addListener:()=>()=>{}};
 const {packCloudSave,unpackCloudSave}=await import('../lib/cloud-save-codec.mjs');let record,applied;const oldFetch=global.fetch;
 global.fetch=async(url,options={})=>{let data;if(url.includes('entitlements')) data={maxSaves:25,currentSaves:1,remainingSaves:24,tier:'paid'};else if(options.method==='POST'){const body=JSON.parse(options.body);record={id:'one',name:body.name,save_type:body.saveType,data:unpackCloudSave(packCloudSave(body.saveType,body.data).packed).data};data=record;}else if(url.includes('/saves/'))data=record;else data={saves:record?[record]:[]};return Response.json(data);};
 const useCloudVault=hook();let vault;const build={race:'Breton',sign:'The Mage',className:'Mage',bitterCup:true,loadouts:[{id:'one',items:{}}]};function Harness(){vault=useCloudVault({activeBuild:build,onApplyBuild:b=>{applied=b;}});return null;}
 const root=createRoot(document.getElementById('root'));try{await act(async()=>root.render(React.createElement(Harness)));await act(async()=>{await vault.saveActiveBuild('Test');});assert.equal(record.data.race,'Breton');assert.equal(record.data.bitterCup,true);assert.equal(vault.entitlements.maxSaves,25);await act(async()=>{const res=await vault.loadSaveIntoSession('one');assert.equal(res.success,true);});assert.equal(applied.race,'Breton');await act(async()=>{const res=await vault.duplicateSave('one');assert.equal(res.success,true);});assert.equal(record.name,'Test (Copy)');}finally{await act(async()=>root.unmount());global.fetch=oldFetch;dom.window.close();}
});

test('saving an imported character uses OpenMW payload and preserves level and progress',async()=>{
 const dom=new JSDOM('<div id="root"></div>',{url:'https://site.test'});global.window=dom.window;global.document=dom.window.document;global.IS_REACT_ACT_ENVIRONMENT=true;
 window.Clerk={user:{id:'one'},session:{getToken:async()=> 'token'},addListener:()=>()=>{}};
 const {packCloudSave,unpackCloudSave,extractCloudSaveMetadata}=await import('../lib/cloud-save-codec.mjs');let record;const oldFetch=global.fetch;
 const save={formatVersion:37,contentFiles:['Morrowind.esm','Tamriel_Data.esm','TR_Mainland.esm','ARCE.esp'],identity:{name:'Test Cat',race:'khajiit',level:8,class:{id:'cat',name:'Cat',custom:true},birthsign:'thief',cell:'Balmora'},vitals:{gold:250},build:{skills:[],attributes:[]},progress:{quests:[{id:'test',stage:20,finished:false}],factions:[],otherJournalIds:[]},stuff:{inventory:[{id:'iron dagger',count:1}],spells:[],equipped:{}}};
 global.fetch=async(url,options={})=>{let data;if(url.includes('entitlements'))data={maxSaves:5,currentSaves:1};else if(options.method==='POST'){const body=JSON.parse(options.body);record={save_type:body.saveType,data:unpackCloudSave(packCloudSave(body.saveType,body.data).packed).data};data=record;}else data={saves:[]};return Response.json(data);};
 const useCloudVault=hook();let vault;function Harness(){vault=useCloudVault({activeBuild:{race:'Khajiit',className:'Custom'},activeSave:{save}});return null;}
 const root=createRoot(document.getElementById('root'));try{await act(async()=>root.render(React.createElement(Harness)));await act(async()=>{const result=await vault.saveActiveBuild();assert.equal(result.success,true);});assert.equal(record.save_type,'openmw_save');assert.equal(record.data.identity.level,8);assert.equal(record.data.identity.class.name,'Cat');assert.equal(record.data.vitals.gold,250);assert.equal(record.data.progress.quests[0].stage,20);assert.equal(record.data.stuff.inventory[0].id,'iron dagger');assert.deepEqual(record.data.contentFiles,save.contentFiles);}finally{await act(async()=>root.unmount());global.fetch=oldFetch;dom.window.close();}
});
