/** Handcrafted premade character builds from verified classic data */
export const BUILDS = [
  {
    "cat": "Pure mage",
    "name": "Altmer Atronach Spellweaver",
    "race": "High Elf",
    "gender": "Female",
    "spec": "Magic",
    "fav": "Intelligence, Willpower",
    "maj": "Destruction, Alteration, Mysticism, Enchant, Alchemy",
    "min": "Illusion, Restoration, Unarmored, Conjuration, Mercantile",
    "sign": "The Atronach"
  },
  {
    "cat": "Pure mage",
    "name": "Breton Apprentice Nuker",
    "race": "Breton",
    "gender": "Male",
    "spec": "Magic",
    "fav": "Intelligence, Willpower",
    "maj": "Destruction, Restoration, Alteration, Illusion, Mysticism",
    "min": "Alchemy, Enchant, Conjuration, Unarmored, Speechcraft",
    "sign": "The Apprentice"
  },
  {
    "cat": "Pure mage",
    "name": "Altmer Mage The Mage",
    "race": "High Elf",
    "gender": "Male",
    "spec": "Magic",
    "fav": "Intelligence, Willpower",
    "maj": "Destruction, Alteration, Restoration, Mysticism, Alchemy",
    "min": "Illusion, Enchant, Unarmored, Conjuration, Mercantile",
    "sign": "The Mage"
  },
  {
    "cat": "Pure mage",
    "name": "Breton Atronach Scholar",
    "race": "Breton",
    "gender": "Female",
    "spec": "Magic",
    "fav": "Intelligence, Personality",
    "maj": "Mysticism, Enchant, Alchemy, Destruction, Restoration",
    "min": "Alteration, Illusion, Mercantile, Speechcraft, Unarmored",
    "sign": "The Atronach"
  },
  {
    "cat": "Pure mage",
    "name": "Dunmer Fire Mage",
    "race": "Dark Elf",
    "gender": "Female",
    "spec": "Magic",
    "fav": "Intelligence, Speed",
    "maj": "Destruction, Alteration, Mysticism, Athletics, Restoration",
    "min": "Alchemy, Enchant, Light Armor, Illusion, Mercantile",
    "sign": "The Mage"
  },
  {
    "cat": "Battlemage",
    "name": "Redguard Lady Spellsword",
    "race": "Redguard",
    "gender": "Male",
    "spec": "Combat",
    "fav": "Strength, Endurance",
    "maj": "Long Blade, Heavy Armor, Destruction, Restoration, Athletics",
    "min": "Block, Armorer, Alteration, Alchemy, Mercantile",
    "sign": "The Lady"
  },
  {
    "cat": "Battlemage",
    "name": "Nord Warrior Axe-Mage",
    "race": "Nord",
    "gender": "Male",
    "spec": "Combat",
    "fav": "Strength, Endurance",
    "maj": "Axe, Medium Armor, Block, Destruction, Restoration",
    "min": "Athletics, Armorer, Alteration, Alchemy, Speechcraft",
    "sign": "The Warrior"
  },
  {
    "cat": "Battlemage",
    "name": "Orc Lady Crusader-Mage",
    "race": "Orc",
    "gender": "Female",
    "spec": "Combat",
    "fav": "Endurance, Willpower",
    "maj": "Blunt Weapon, Heavy Armor, Restoration, Destruction, Block",
    "min": "Armorer, Athletics, Alteration, Alchemy, Mercantile",
    "sign": "The Lady"
  },
  {
    "cat": "Battlemage",
    "name": "Imperial Knight of Stendarr",
    "race": "Imperial",
    "gender": "Male",
    "spec": "Combat",
    "fav": "Personality, Endurance",
    "maj": "Long Blade, Heavy Armor, Restoration, Block, Speechcraft",
    "min": "Destruction, Athletics, Armorer, Mercantile, Illusion",
    "sign": "The Lady"
  },
  {
    "cat": "Battlemage",
    "name": "Breton Spellsword Lady",
    "race": "Breton",
    "gender": "Female",
    "spec": "Magic",
    "fav": "Willpower, Endurance",
    "maj": "Long Blade, Destruction, Restoration, Alteration, Medium Armor",
    "min": "Block, Mysticism, Athletics, Alchemy, Enchant",
    "sign": "The Lady"
  },
  {
    "cat": "Pure melee",
    "name": "Orc Endurance Crusher",
    "race": "Orc",
    "gender": "Male",
    "spec": "Combat",
    "fav": "Strength, Endurance",
    "maj": "Blunt Weapon, Heavy Armor, Block, Armorer, Athletics",
    "min": "Axe, Medium Armor, Spear, Acrobatics, Mercantile",
    "sign": "The Lady"
  },
  {
    "cat": "Pure melee",
    "name": "Nord Warrior Spearman",
    "race": "Nord",
    "gender": "Male",
    "spec": "Combat",
    "fav": "Strength, Endurance",
    "maj": "Spear, Medium Armor, Block, Athletics, Armorer",
    "min": "Axe, Heavy Armor, Acrobatics, Restoration, Mercantile",
    "sign": "The Warrior"
  },
  {
    "cat": "Pure melee",
    "name": "Redguard Long Blade Duelist",
    "race": "Redguard",
    "gender": "Female",
    "spec": "Combat",
    "fav": "Strength, Speed",
    "maj": "Long Blade, Medium Armor, Athletics, Block, Armorer",
    "min": "Acrobatics, Light Armor, Restoration, Mercantile, Speechcraft",
    "sign": "The Warrior"
  },
  {
    "cat": "Pure melee",
    "name": "Imperial Legionnaire",
    "race": "Imperial",
    "gender": "Male",
    "spec": "Combat",
    "fav": "Personality, Endurance",
    "maj": "Long Blade, Heavy Armor, Block, Speechcraft, Athletics",
    "min": "Armorer, Restoration, Mercantile, Medium Armor, Spear",
    "sign": "The Lady"
  },
  {
    "cat": "Pure melee",
    "name": "Nord Steed Berserker",
    "race": "Nord",
    "gender": "Female",
    "spec": "Combat",
    "fav": "Strength, Speed",
    "maj": "Axe, Medium Armor, Athletics, Acrobatics, Block",
    "min": "Armorer, Restoration, Light Armor, Spear, Mercantile",
    "sign": "The Steed"
  },
  {
    "cat": "Assassin",
    "name": "Khajiit Nightblade",
    "race": "Khajiit",
    "gender": "Male",
    "spec": "Stealth",
    "fav": "Speed, Agility",
    "maj": "Short Blade, Sneak, Light Armor, Security, Illusion",
    "min": "Marksman, Acrobatics, Athletics, Alchemy, Mercantile",
    "sign": "The Thief"
  },
  {
    "cat": "Assassin",
    "name": "Bosmer Archer Assassin",
    "race": "Wood Elf",
    "gender": "Female",
    "spec": "Stealth",
    "fav": "Agility, Speed",
    "maj": "Marksman, Sneak, Light Armor, Alchemy, Athletics",
    "min": "Short Blade, Security, Acrobatics, Illusion, Mercantile",
    "sign": "The Thief"
  },
  {
    "cat": "Assassin",
    "name": "Dunmer Shadowblade",
    "race": "Dark Elf",
    "gender": "Female",
    "spec": "Stealth",
    "fav": "Speed, Willpower",
    "maj": "Short Blade, Sneak, Light Armor, Illusion, Destruction",
    "min": "Marksman, Athletics, Alchemy, Security, Mysticism",
    "sign": "The Thief"
  },
  {
    "cat": "Assassin",
    "name": "Imperial Agent",
    "race": "Imperial",
    "gender": "Male",
    "spec": "Stealth",
    "fav": "Personality, Agility",
    "maj": "Short Blade, Speechcraft, Light Armor, Sneak, Mercantile",
    "min": "Security, Illusion, Athletics, Marksman, Restoration",
    "sign": "The Lover"
  },
  {
    "cat": "Assassin",
    "name": "Khajiit Shadow The Shadow",
    "race": "Khajiit",
    "gender": "Female",
    "spec": "Stealth",
    "fav": "Speed, Luck",
    "maj": "Sneak, Short Blade, Light Armor, Security, Acrobatics",
    "min": "Illusion, Marksman, Athletics, Alchemy, Mercantile",
    "sign": "The Shadow"
  },
  {
    "cat": "Archer",
    "name": "Bosmer Hunter",
    "race": "Wood Elf",
    "gender": "Male",
    "spec": "Stealth",
    "fav": "Agility, Speed",
    "maj": "Marksman, Sneak, Light Armor, Athletics, Alchemy",
    "min": "Short Blade, Acrobatics, Restoration, Mercantile, Security",
    "sign": "The Thief"
  },
  {
    "cat": "Archer",
    "name": "Imperial Scout Bowman",
    "race": "Imperial",
    "gender": "Female",
    "spec": "Stealth",
    "fav": "Agility, Endurance",
    "maj": "Marksman, Sneak, Light Armor, Athletics, Restoration",
    "min": "Acrobatics, Block, Mercantile, Speechcraft, Armorer",
    "sign": "The Lady"
  },
  {
    "cat": "Archer",
    "name": "Redguard Ranger",
    "race": "Redguard",
    "gender": "Male",
    "spec": "Combat",
    "fav": "Agility, Strength",
    "maj": "Marksman, Long Blade, Athletics, Medium Armor, Restoration",
    "min": "Block, Armorer, Acrobatics, Mercantile, Alchemy",
    "sign": "The Warrior"
  },
  {
    "cat": "Archer",
    "name": "Dunmer Ashlands Archer",
    "race": "Dark Elf",
    "gender": "Female",
    "spec": "Stealth",
    "fav": "Agility, Speed",
    "maj": "Marksman, Light Armor, Athletics, Destruction, Sneak",
    "min": "Short Blade, Alchemy, Restoration, Acrobatics, Mercantile",
    "sign": "The Thief"
  },
  {
    "cat": "Thief",
    "name": "Khajiit Cutpurse",
    "race": "Khajiit",
    "gender": "Male",
    "spec": "Stealth",
    "fav": "Agility, Personality",
    "maj": "Security, Sneak, Short Blade, Mercantile, Light Armor",
    "min": "Speechcraft, Acrobatics, Athletics, Illusion, Marksman",
    "sign": "The Thief"
  },
  {
    "cat": "Thief",
    "name": "Bosmer Guild Rat",
    "race": "Wood Elf",
    "gender": "Female",
    "spec": "Stealth",
    "fav": "Agility, Speed",
    "maj": "Sneak, Security, Marksman, Light Armor, Acrobatics",
    "min": "Short Blade, Mercantile, Athletics, Illusion, Alchemy",
    "sign": "The Lover"
  },
  {
    "cat": "Thief",
    "name": "Imperial Fence",
    "race": "Imperial",
    "gender": "Male",
    "spec": "Stealth",
    "fav": "Personality, Luck",
    "maj": "Speechcraft, Mercantile, Security, Sneak, Short Blade",
    "min": "Light Armor, Illusion, Athletics, Restoration, Acrobatics",
    "sign": "The Thief"
  },
  {
    "cat": "Healer",
    "name": "Breton Temple Healer",
    "race": "Breton",
    "gender": "Female",
    "spec": "Magic",
    "fav": "Willpower, Personality",
    "maj": "Restoration, Mysticism, Alchemy, Speechcraft, Unarmored",
    "min": "Alteration, Illusion, Mercantile, Destruction, Enchant",
    "sign": "The Ritual"
  },
  {
    "cat": "Healer",
    "name": "Imperial Cult Chaplain",
    "race": "Imperial",
    "gender": "Male",
    "spec": "Magic",
    "fav": "Personality, Willpower",
    "maj": "Restoration, Speechcraft, Mercantile, Illusion, Alchemy",
    "min": "Mysticism, Unarmored, Destruction, Athletics, Enchant",
    "sign": "The Ritual"
  },
  {
    "cat": "Healer",
    "name": "Altmer Restorer",
    "race": "High Elf",
    "gender": "Female",
    "spec": "Magic",
    "fav": "Willpower, Intelligence",
    "maj": "Restoration, Alteration, Mysticism, Alchemy, Enchant",
    "min": "Destruction, Illusion, Unarmored, Mercantile, Speechcraft",
    "sign": "The Mage"
  },
  {
    "cat": "Monk",
    "name": "Redguard Hand-to-Hand",
    "race": "Redguard",
    "gender": "Male",
    "spec": "Stealth",
    "fav": "Speed, Endurance",
    "maj": "Hand-to-hand, Unarmored, Acrobatics, Sneak, Light Armor",
    "min": "Athletics, Restoration, Alchemy, Speechcraft, Block",
    "sign": "The Lady"
  },
  {
    "cat": "Monk",
    "name": "Argonian Marsh Monk",
    "race": "Argonian",
    "gender": "Female",
    "spec": "Stealth",
    "fav": "Speed, Agility",
    "maj": "Hand-to-hand, Unarmored, Acrobatics, Sneak, Athletics",
    "min": "Restoration, Spear, Light Armor, Mysticism, Illusion",
    "sign": "The Lady"
  },
  {
    "cat": "Monk",
    "name": "Khajiit Acrobat Monk",
    "race": "Khajiit",
    "gender": "Male",
    "spec": "Stealth",
    "fav": "Speed, Agility",
    "maj": "Acrobatics, Hand-to-hand, Unarmored, Athletics, Sneak",
    "min": "Short Blade, Restoration, Light Armor, Security, Mercantile",
    "sign": "The Steed"
  },
  {
    "cat": "Spearman",
    "name": "Argonian Spear Scout",
    "race": "Argonian",
    "gender": "Male",
    "spec": "Combat",
    "fav": "Endurance, Speed",
    "maj": "Spear, Medium Armor, Athletics, Restoration, Alchemy",
    "min": "Block, Unarmored, Sneak, Acrobatics, Mercantile",
    "sign": "The Lady"
  },
  {
    "cat": "Spearman",
    "name": "Nord Reach Fighter",
    "race": "Nord",
    "gender": "Female",
    "spec": "Combat",
    "fav": "Strength, Endurance",
    "maj": "Spear, Heavy Armor, Block, Athletics, Armorer",
    "min": "Axe, Restoration, Medium Armor, Acrobatics, Mercantile",
    "sign": "The Warrior"
  },
  {
    "cat": "Enchanter",
    "name": "Altmer Soulbinder",
    "race": "High Elf",
    "gender": "Male",
    "spec": "Magic",
    "fav": "Intelligence, Willpower",
    "maj": "Enchant, Mysticism, Conjuration, Destruction, Alchemy",
    "min": "Alteration, Restoration, Unarmored, Mercantile, Illusion",
    "sign": "The Atronach"
  },
  {
    "cat": "Enchanter",
    "name": "Breton Artificer",
    "race": "Breton",
    "gender": "Female",
    "spec": "Magic",
    "fav": "Intelligence, Personality",
    "maj": "Enchant, Alchemy, Mysticism, Restoration, Mercantile",
    "min": "Destruction, Alteration, Illusion, Unarmored, Speechcraft",
    "sign": "The Mage"
  },
  {
    "cat": "Alchemist",
    "name": "Bosmer Poisoner",
    "race": "Wood Elf",
    "gender": "Female",
    "spec": "Magic",
    "fav": "Intelligence, Agility",
    "maj": "Alchemy, Restoration, Destruction, Enchant, Illusion",
    "min": "Light Armor, Marksman, Athletics, Security, Sneak",
    "sign": "The Thief"
  },
  {
    "cat": "Alchemist",
    "name": "Argonian Marsh Mixer",
    "race": "Argonian",
    "gender": "Male",
    "spec": "Magic",
    "fav": "Intelligence, Speed",
    "maj": "Alchemy, Restoration, Athletics, Unarmored, Mysticism",
    "min": "Spear, Alteration, Mercantile, Illusion, Enchant",
    "sign": "The Mage"
  },
  {
    "cat": "Conjurer",
    "name": "Breton Summoner",
    "race": "Breton",
    "gender": "Male",
    "spec": "Magic",
    "fav": "Willpower, Intelligence",
    "maj": "Conjuration, Mysticism, Destruction, Restoration, Enchant",
    "min": "Alteration, Alchemy, Unarmored, Illusion, Mercantile",
    "sign": "The Apprentice"
  },
  {
    "cat": "Conjurer",
    "name": "Dunmer Daedric Binder",
    "race": "Dark Elf",
    "gender": "Female",
    "spec": "Magic",
    "fav": "Willpower, Speed",
    "maj": "Conjuration, Destruction, Mysticism, Light Armor, Restoration",
    "min": "Alteration, Enchant, Alchemy, Athletics, Illusion",
    "sign": "The Mage"
  }
];

export const RACE_BUILDS = [
  {
    "cat": "High Elf",
    "name": "High Elf male — Atronach mage",
    "race": "High Elf",
    "gender": "Male",
    "spec": "Magic",
    "fav": "Intelligence, Willpower",
    "maj": "Destruction, Alteration, Mysticism, Enchant, Alchemy",
    "min": "Illusion, Restoration, Unarmored, Conjuration, Mercantile",
    "sign": "The Atronach"
  },
  {
    "cat": "High Elf",
    "name": "High Elf female — Atronach mage",
    "race": "High Elf",
    "gender": "Female",
    "spec": "Magic",
    "fav": "Intelligence, Willpower",
    "maj": "Destruction, Alteration, Mysticism, Enchant, Alchemy",
    "min": "Illusion, Restoration, Unarmored, Conjuration, Mercantile",
    "sign": "The Atronach"
  },
  {
    "cat": "Argonian",
    "name": "Argonian male — Spear scout",
    "race": "Argonian",
    "gender": "Male",
    "spec": "Combat",
    "fav": "Endurance, Speed",
    "maj": "Spear, Medium Armor, Athletics, Restoration, Alchemy",
    "min": "Block, Unarmored, Sneak, Acrobatics, Mercantile",
    "sign": "The Lady"
  },
  {
    "cat": "Argonian",
    "name": "Argonian female — Marsh mage",
    "race": "Argonian",
    "gender": "Female",
    "spec": "Magic",
    "fav": "Intelligence, Speed",
    "maj": "Alchemy, Restoration, Athletics, Unarmored, Mysticism",
    "min": "Spear, Alteration, Mercantile, Illusion, Enchant",
    "sign": "The Mage"
  },
  {
    "cat": "Breton",
    "name": "Breton male — Apprentice nuker",
    "race": "Breton",
    "gender": "Male",
    "spec": "Magic",
    "fav": "Intelligence, Willpower",
    "maj": "Destruction, Restoration, Alteration, Illusion, Mysticism",
    "min": "Alchemy, Enchant, Conjuration, Unarmored, Speechcraft",
    "sign": "The Apprentice"
  },
  {
    "cat": "Breton",
    "name": "Breton female — Atronach scholar",
    "race": "Breton",
    "gender": "Female",
    "spec": "Magic",
    "fav": "Intelligence, Personality",
    "maj": "Mysticism, Enchant, Alchemy, Destruction, Restoration",
    "min": "Alteration, Illusion, Mercantile, Speechcraft, Unarmored",
    "sign": "The Atronach"
  },
  {
    "cat": "Dark Elf",
    "name": "Dark Elf male — Fire battlemage",
    "race": "Dark Elf",
    "gender": "Male",
    "spec": "Magic",
    "fav": "Intelligence, Speed",
    "maj": "Destruction, Restoration, Alteration, Long Blade, Light Armor",
    "min": "Mysticism, Alchemy, Enchant, Illusion, Mercantile",
    "sign": "The Mage"
  },
  {
    "cat": "Dark Elf",
    "name": "Dark Elf female — Shadowblade",
    "race": "Dark Elf",
    "gender": "Female",
    "spec": "Stealth",
    "fav": "Speed, Willpower",
    "maj": "Short Blade, Sneak, Light Armor, Illusion, Destruction",
    "min": "Marksman, Athletics, Alchemy, Security, Mysticism",
    "sign": "The Thief"
  },
  {
    "cat": "Imperial",
    "name": "Imperial male — Legion knight",
    "race": "Imperial",
    "gender": "Male",
    "spec": "Combat",
    "fav": "Personality, Endurance",
    "maj": "Long Blade, Heavy Armor, Block, Speechcraft, Athletics",
    "min": "Armorer, Restoration, Mercantile, Medium Armor, Spear",
    "sign": "The Lady"
  },
  {
    "cat": "Imperial",
    "name": "Imperial female — Agent",
    "race": "Imperial",
    "gender": "Female",
    "spec": "Stealth",
    "fav": "Personality, Agility",
    "maj": "Short Blade, Speechcraft, Light Armor, Sneak, Mercantile",
    "min": "Security, Illusion, Athletics, Marksman, Restoration",
    "sign": "The Lover"
  },
  {
    "cat": "Khajiit",
    "name": "Khajiit male — Nightblade",
    "race": "Khajiit",
    "gender": "Male",
    "spec": "Stealth",
    "fav": "Speed, Agility",
    "maj": "Short Blade, Sneak, Light Armor, Security, Illusion",
    "min": "Marksman, Acrobatics, Athletics, Alchemy, Mercantile",
    "sign": "The Thief"
  },
  {
    "cat": "Khajiit",
    "name": "Khajiit female — Shadow acrobat",
    "race": "Khajiit",
    "gender": "Female",
    "spec": "Stealth",
    "fav": "Speed, Luck",
    "maj": "Sneak, Short Blade, Light Armor, Security, Acrobatics",
    "min": "Illusion, Marksman, Athletics, Alchemy, Mercantile",
    "sign": "The Shadow"
  },
  {
    "cat": "Nord",
    "name": "Nord male — Warrior axe",
    "race": "Nord",
    "gender": "Male",
    "spec": "Combat",
    "fav": "Strength, Endurance",
    "maj": "Axe, Medium Armor, Block, Athletics, Armorer",
    "min": "Heavy Armor, Restoration, Acrobatics, Spear, Mercantile",
    "sign": "The Warrior"
  },
  {
    "cat": "Nord",
    "name": "Nord female — Steed berserker",
    "race": "Nord",
    "gender": "Female",
    "spec": "Combat",
    "fav": "Strength, Speed",
    "maj": "Axe, Medium Armor, Athletics, Acrobatics, Block",
    "min": "Armorer, Restoration, Light Armor, Spear, Mercantile",
    "sign": "The Steed"
  },
  {
    "cat": "Orc",
    "name": "Orc male — Endurance crusher",
    "race": "Orc",
    "gender": "Male",
    "spec": "Combat",
    "fav": "Strength, Endurance",
    "maj": "Blunt Weapon, Heavy Armor, Block, Armorer, Athletics",
    "min": "Axe, Medium Armor, Spear, Acrobatics, Mercantile",
    "sign": "The Lady"
  },
  {
    "cat": "Orc",
    "name": "Orc female — Lady crusader",
    "race": "Orc",
    "gender": "Female",
    "spec": "Combat",
    "fav": "Endurance, Willpower",
    "maj": "Blunt Weapon, Heavy Armor, Restoration, Destruction, Block",
    "min": "Armorer, Athletics, Alteration, Alchemy, Mercantile",
    "sign": "The Lady"
  },
  {
    "cat": "Redguard",
    "name": "Redguard male — Lady spellsword",
    "race": "Redguard",
    "gender": "Male",
    "spec": "Combat",
    "fav": "Strength, Endurance",
    "maj": "Long Blade, Heavy Armor, Destruction, Restoration, Athletics",
    "min": "Block, Armorer, Alteration, Alchemy, Mercantile",
    "sign": "The Lady"
  },
  {
    "cat": "Redguard",
    "name": "Redguard female — Long Blade duelist",
    "race": "Redguard",
    "gender": "Female",
    "spec": "Combat",
    "fav": "Strength, Speed",
    "maj": "Long Blade, Medium Armor, Athletics, Block, Armorer",
    "min": "Acrobatics, Light Armor, Restoration, Mercantile, Speechcraft",
    "sign": "The Warrior"
  },
  {
    "cat": "Wood Elf",
    "name": "Wood Elf male — Hunter",
    "race": "Wood Elf",
    "gender": "Male",
    "spec": "Stealth",
    "fav": "Agility, Speed",
    "maj": "Marksman, Sneak, Light Armor, Athletics, Alchemy",
    "min": "Short Blade, Acrobatics, Restoration, Mercantile, Security",
    "sign": "The Thief"
  },
  {
    "cat": "Wood Elf",
    "name": "Wood Elf female — Archer assassin",
    "race": "Wood Elf",
    "gender": "Female",
    "spec": "Stealth",
    "fav": "Agility, Speed",
    "maj": "Marksman, Sneak, Light Armor, Alchemy, Athletics",
    "min": "Short Blade, Security, Acrobatics, Illusion, Mercantile",
    "sign": "The Thief"
  }
];

export const ARCE_BUILDS = [
  {
    "cat": "Tsaesci",
    "name": "Tsaesci male — Unarmored and Long Blade",
    "race": "Tsaesci",
    "gender": "Male",
    "spec": "Combat",
    "fav": "Speed, Strength",
    "maj": "Unarmored, Long Blade, Athletics, Medium Armor, Speechcraft",
    "min": "Block, Armorer, Heavy Armor, Axe, Blunt Weapon",
    "sign": "The Warrior"
  },
  {
    "cat": "Tsaesci",
    "name": "Tsaesci female — Unarmored and Long Blade",
    "race": "Tsaesci",
    "gender": "Female",
    "spec": "Combat",
    "fav": "Speed, Strength",
    "maj": "Unarmored, Long Blade, Athletics, Medium Armor, Speechcraft",
    "min": "Block, Armorer, Heavy Armor, Axe, Blunt Weapon",
    "sign": "The Warrior"
  },
  {
    "cat": "Naga",
    "name": "Naga male — Unarmored and Blunt Weapon",
    "race": "Naga",
    "gender": "Male",
    "spec": "Magic",
    "fav": "Speed, Strength",
    "maj": "Unarmored, Blunt Weapon, Athletics, Alteration, Restoration",
    "min": "Sneak, Hand-to-hand, Destruction, Mysticism, Conjuration",
    "sign": "The Mage"
  },
  {
    "cat": "Naga",
    "name": "Naga female — Unarmored and Blunt Weapon",
    "race": "Naga",
    "gender": "Female",
    "spec": "Magic",
    "fav": "Speed, Strength",
    "maj": "Unarmored, Blunt Weapon, Athletics, Alteration, Restoration",
    "min": "Sneak, Hand-to-hand, Destruction, Mysticism, Conjuration",
    "sign": "The Mage"
  },
  {
    "cat": "Chimeri-Quey",
    "name": "Chimeri-Quey male — Mysticism and Mercantile",
    "race": "Chimeri-Quey",
    "gender": "Male",
    "spec": "Stealth",
    "fav": "Willpower, Personality",
    "maj": "Mysticism, Mercantile, Speechcraft, Axe, Sneak",
    "min": "Conjuration, Acrobatics, Security, Light Armor, Short Blade",
    "sign": "The Thief"
  },
  {
    "cat": "Chimeri-Quey",
    "name": "Chimeri-Quey female — Mysticism and Mercantile",
    "race": "Chimeri-Quey",
    "gender": "Female",
    "spec": "Stealth",
    "fav": "Willpower, Personality",
    "maj": "Mysticism, Mercantile, Speechcraft, Axe, Sneak",
    "min": "Conjuration, Acrobatics, Security, Light Armor, Short Blade",
    "sign": "The Thief"
  },
  {
    "cat": "Keptu-Quey",
    "name": "Keptu-Quey male — Blunt Weapon and Block",
    "race": "Keptu-Quey",
    "gender": "Male",
    "spec": "Combat",
    "fav": "Strength, Agility",
    "maj": "Blunt Weapon, Block, Armorer, Heavy Armor, Unarmored",
    "min": "Hand-to-hand, Athletics, Medium Armor, Long Blade, Axe",
    "sign": "The Warrior"
  },
  {
    "cat": "Keptu-Quey",
    "name": "Keptu-Quey female — Blunt Weapon and Block",
    "race": "Keptu-Quey",
    "gender": "Female",
    "spec": "Combat",
    "fav": "Strength, Agility",
    "maj": "Blunt Weapon, Block, Armorer, Heavy Armor, Unarmored",
    "min": "Hand-to-hand, Athletics, Medium Armor, Long Blade, Axe",
    "sign": "The Warrior"
  },
  {
    "cat": "Ayleid",
    "name": "Ayleid male — Enchant and Alteration",
    "race": "Ayleid",
    "gender": "Male",
    "spec": "Magic",
    "fav": "Intelligence, Willpower",
    "maj": "Enchant, Alteration, Illusion, Conjuration, Mysticism",
    "min": "Restoration, Destruction, Alchemy, Unarmored, Athletics",
    "sign": "The Mage"
  },
  {
    "cat": "Ayleid",
    "name": "Ayleid female — Enchant and Alteration",
    "race": "Ayleid",
    "gender": "Female",
    "spec": "Magic",
    "fav": "Intelligence, Willpower",
    "maj": "Enchant, Alteration, Illusion, Conjuration, Mysticism",
    "min": "Restoration, Destruction, Alchemy, Unarmored, Athletics",
    "sign": "The Mage"
  },
  {
    "cat": "Khajiit (Cathay)",
    "name": "Khajiit (Cathay) male — Athletics and Security",
    "race": "Khajiit (Cathay)",
    "gender": "Male",
    "spec": "Stealth",
    "fav": "Speed, Intelligence",
    "maj": "Athletics, Security, Long Blade, Acrobatics, Sneak",
    "min": "Spear, Light Armor, Short Blade, Marksman, Speechcraft",
    "sign": "The Thief"
  },
  {
    "cat": "Khajiit (Cathay)",
    "name": "Khajiit (Cathay) female — Athletics and Security",
    "race": "Khajiit (Cathay)",
    "gender": "Female",
    "spec": "Stealth",
    "fav": "Speed, Intelligence",
    "maj": "Athletics, Security, Long Blade, Acrobatics, Sneak",
    "min": "Spear, Light Armor, Short Blade, Marksman, Speechcraft",
    "sign": "The Thief"
  },
  {
    "cat": "Khajiit (Cathay-raht)",
    "name": "Khajiit (Cathay-raht) male — Athletics and Long Blade",
    "race": "Khajiit (Cathay-raht)",
    "gender": "Male",
    "spec": "Combat",
    "fav": "Speed, Strength",
    "maj": "Athletics, Long Blade, Light Armor, Sneak, Block",
    "min": "Short Blade, Armorer, Medium Armor, Heavy Armor, Axe",
    "sign": "The Warrior"
  },
  {
    "cat": "Khajiit (Cathay-raht)",
    "name": "Khajiit (Cathay-raht) female — Athletics and Long Blade",
    "race": "Khajiit (Cathay-raht)",
    "gender": "Female",
    "spec": "Combat",
    "fav": "Speed, Strength",
    "maj": "Athletics, Long Blade, Light Armor, Sneak, Block",
    "min": "Short Blade, Armorer, Medium Armor, Heavy Armor, Axe",
    "sign": "The Warrior"
  },
  {
    "cat": "Khajiit (Dagi-raht)",
    "name": "Khajiit (Dagi-raht) male — Acrobatics and Sneak",
    "race": "Khajiit (Dagi-raht)",
    "gender": "Male",
    "spec": "Stealth",
    "fav": "Strength, Agility",
    "maj": "Acrobatics, Sneak, Athletics, Destruction, Security",
    "min": "Illusion, Hand-to-hand, Light Armor, Short Blade, Marksman",
    "sign": "The Thief"
  },
  {
    "cat": "Khajiit (Dagi-raht)",
    "name": "Khajiit (Dagi-raht) female — Acrobatics and Sneak",
    "race": "Khajiit (Dagi-raht)",
    "gender": "Female",
    "spec": "Stealth",
    "fav": "Strength, Agility",
    "maj": "Acrobatics, Sneak, Athletics, Destruction, Security",
    "min": "Illusion, Hand-to-hand, Light Armor, Short Blade, Marksman",
    "sign": "The Thief"
  },
  {
    "cat": "Khajiit (Ohmes)",
    "name": "Khajiit (Ohmes) male — Acrobatics and Speechcraft",
    "race": "Khajiit (Ohmes)",
    "gender": "Male",
    "spec": "Stealth",
    "fav": "Strength, Personality",
    "maj": "Acrobatics, Speechcraft, Security, Sneak, Light Armor",
    "min": "Short Blade, Mercantile, Marksman, Hand-to-hand, Athletics",
    "sign": "The Thief"
  },
  {
    "cat": "Khajiit (Ohmes)",
    "name": "Khajiit (Ohmes) female — Acrobatics and Speechcraft",
    "race": "Khajiit (Ohmes)",
    "gender": "Female",
    "spec": "Stealth",
    "fav": "Strength, Personality",
    "maj": "Acrobatics, Speechcraft, Security, Sneak, Light Armor",
    "min": "Short Blade, Mercantile, Marksman, Hand-to-hand, Athletics",
    "sign": "The Thief"
  },
  {
    "cat": "Khajiit (Ohmes-raht)",
    "name": "Khajiit (Ohmes-raht) male — Acrobatics and Sneak",
    "race": "Khajiit (Ohmes-raht)",
    "gender": "Male",
    "spec": "Stealth",
    "fav": "Strength, Agility",
    "maj": "Acrobatics, Sneak, Illusion, Security, Light Armor",
    "min": "Speechcraft, Short Blade, Marksman, Mercantile, Hand-to-hand",
    "sign": "The Thief"
  },
  {
    "cat": "Khajiit (Ohmes-raht)",
    "name": "Khajiit (Ohmes-raht) female — Acrobatics and Sneak",
    "race": "Khajiit (Ohmes-raht)",
    "gender": "Female",
    "spec": "Stealth",
    "fav": "Strength, Agility",
    "maj": "Acrobatics, Sneak, Illusion, Security, Light Armor",
    "min": "Speechcraft, Short Blade, Marksman, Mercantile, Hand-to-hand",
    "sign": "The Thief"
  },
  {
    "cat": "Khajiit (Suthay)",
    "name": "Khajiit (Suthay) male — Acrobatics and Sneak",
    "race": "Khajiit (Suthay)",
    "gender": "Male",
    "spec": "Stealth",
    "fav": "Strength, Agility",
    "maj": "Acrobatics, Sneak, Security, Light Armor, Short Blade",
    "min": "Hand-to-hand, Marksman, Speechcraft, Mercantile, Athletics",
    "sign": "The Thief"
  },
  {
    "cat": "Khajiit (Suthay)",
    "name": "Khajiit (Suthay) female — Acrobatics and Sneak",
    "race": "Khajiit (Suthay)",
    "gender": "Female",
    "spec": "Stealth",
    "fav": "Strength, Agility",
    "maj": "Acrobatics, Sneak, Security, Light Armor, Short Blade",
    "min": "Hand-to-hand, Marksman, Speechcraft, Mercantile, Athletics",
    "sign": "The Thief"
  },
  {
    "cat": "Khajiit (Tojay)",
    "name": "Khajiit (Tojay) male — Restoration and Blunt Weapon",
    "race": "Khajiit (Tojay)",
    "gender": "Male",
    "spec": "Magic",
    "fav": "Willpower, Strength",
    "maj": "Restoration, Blunt Weapon, Mysticism, Alchemy, Unarmored",
    "min": "Alteration, Destruction, Conjuration, Illusion, Enchant",
    "sign": "The Mage"
  },
  {
    "cat": "Khajiit (Tojay)",
    "name": "Khajiit (Tojay) female — Restoration and Blunt Weapon",
    "race": "Khajiit (Tojay)",
    "gender": "Female",
    "spec": "Magic",
    "fav": "Willpower, Strength",
    "maj": "Restoration, Blunt Weapon, Mysticism, Alchemy, Unarmored",
    "min": "Alteration, Destruction, Conjuration, Illusion, Enchant",
    "sign": "The Mage"
  },
  {
    "cat": "Ogre",
    "name": "Ogre male — Unarmored and Blunt Weapon",
    "race": "Ogre",
    "gender": "Male",
    "spec": "Combat",
    "fav": "Speed, Strength",
    "maj": "Unarmored, Blunt Weapon, Hand-to-hand, Axe, Spear",
    "min": "Athletics, Block, Armorer, Medium Armor, Long Blade",
    "sign": "The Warrior"
  },
  {
    "cat": "Ogre",
    "name": "Ogre female — Unarmored and Blunt Weapon",
    "race": "Ogre",
    "gender": "Female",
    "spec": "Combat",
    "fav": "Speed, Strength",
    "maj": "Unarmored, Blunt Weapon, Hand-to-hand, Axe, Spear",
    "min": "Athletics, Block, Armorer, Medium Armor, Long Blade",
    "sign": "The Warrior"
  },
  {
    "cat": "Riverfolk",
    "name": "Riverfolk male — Block and Athletics",
    "race": "Riverfolk",
    "gender": "Male",
    "spec": "Combat",
    "fav": "Agility, Speed",
    "maj": "Block, Athletics, Long Blade, Marksman, Mercantile",
    "min": "Hand-to-hand, Armorer, Medium Armor, Heavy Armor, Axe",
    "sign": "The Warrior"
  },
  {
    "cat": "Riverfolk",
    "name": "Riverfolk female — Block and Athletics",
    "race": "Riverfolk",
    "gender": "Female",
    "spec": "Combat",
    "fav": "Agility, Speed",
    "maj": "Block, Athletics, Long Blade, Marksman, Mercantile",
    "min": "Hand-to-hand, Armorer, Medium Armor, Heavy Armor, Axe",
    "sign": "The Warrior"
  },
  {
    "cat": "Malahk Orc",
    "name": "Malahk Orc male — Medium Armor and Heavy Armor",
    "race": "Malahk Orc",
    "gender": "Male",
    "spec": "Combat",
    "fav": "Endurance, Strength",
    "maj": "Medium Armor, Heavy Armor, Axe, Blunt Weapon, Unarmored",
    "min": "Hand-to-hand, Athletics, Block, Armorer, Long Blade",
    "sign": "The Warrior"
  },
  {
    "cat": "Malahk Orc",
    "name": "Malahk Orc female — Medium Armor and Heavy Armor",
    "race": "Malahk Orc",
    "gender": "Female",
    "spec": "Combat",
    "fav": "Endurance, Strength",
    "maj": "Medium Armor, Heavy Armor, Axe, Blunt Weapon, Unarmored",
    "min": "Hand-to-hand, Athletics, Block, Armorer, Long Blade",
    "sign": "The Warrior"
  },
  {
    "cat": "Sea Elf",
    "name": "Sea Elf male — Destruction and Alteration",
    "race": "Sea Elf",
    "gender": "Male",
    "spec": "Magic",
    "fav": "Willpower, Endurance",
    "maj": "Destruction, Alteration, Spear, Athletics, Illusion",
    "min": "Unarmored, Sneak, Restoration, Mysticism, Conjuration",
    "sign": "The Mage"
  },
  {
    "cat": "Sea Elf",
    "name": "Sea Elf female — Destruction and Alteration",
    "race": "Sea Elf",
    "gender": "Female",
    "spec": "Magic",
    "fav": "Willpower, Endurance",
    "maj": "Destruction, Alteration, Spear, Athletics, Illusion",
    "min": "Unarmored, Sneak, Restoration, Mysticism, Conjuration",
    "sign": "The Mage"
  },
  {
    "cat": "Hill Giant",
    "name": "Hill Giant male — Blunt Weapon and Hand-to-hand",
    "race": "Hill Giant",
    "gender": "Male",
    "spec": "Combat",
    "fav": "Strength, Speed",
    "maj": "Blunt Weapon, Hand-to-hand, Unarmored, Athletics, Block",
    "min": "Armorer, Medium Armor, Long Blade, Heavy Armor, Axe",
    "sign": "The Warrior"
  },
  {
    "cat": "Hill Giant",
    "name": "Hill Giant female — Blunt Weapon and Hand-to-hand",
    "race": "Hill Giant",
    "gender": "Female",
    "spec": "Combat",
    "fav": "Strength, Speed",
    "maj": "Blunt Weapon, Hand-to-hand, Unarmored, Athletics, Block",
    "min": "Armorer, Medium Armor, Long Blade, Heavy Armor, Axe",
    "sign": "The Warrior"
  },
  {
    "cat": "Reachman",
    "name": "Reachman male — Destruction and Conjuration",
    "race": "Reachman",
    "gender": "Male",
    "spec": "Magic",
    "fav": "Willpower, Intelligence",
    "maj": "Destruction, Conjuration, Alchemy, Blunt Weapon, Athletics",
    "min": "Alteration, Restoration, Mysticism, Illusion, Enchant",
    "sign": "The Mage"
  },
  {
    "cat": "Reachman",
    "name": "Reachman female — Destruction and Conjuration",
    "race": "Reachman",
    "gender": "Female",
    "spec": "Magic",
    "fav": "Willpower, Intelligence",
    "maj": "Destruction, Conjuration, Alchemy, Blunt Weapon, Athletics",
    "min": "Alteration, Restoration, Mysticism, Illusion, Enchant",
    "sign": "The Mage"
  },
  {
    "cat": "Imga",
    "name": "Imga male — Speechcraft and Mysticism",
    "race": "Imga",
    "gender": "Male",
    "spec": "Stealth",
    "fav": "Personality, Willpower",
    "maj": "Speechcraft, Mysticism, Hand-to-hand, Acrobatics, Mercantile",
    "min": "Sneak, Security, Light Armor, Short Blade, Marksman",
    "sign": "The Thief"
  },
  {
    "cat": "Imga",
    "name": "Imga female — Speechcraft and Mysticism",
    "race": "Imga",
    "gender": "Female",
    "spec": "Stealth",
    "fav": "Personality, Willpower",
    "maj": "Speechcraft, Mysticism, Hand-to-hand, Acrobatics, Mercantile",
    "min": "Sneak, Security, Light Armor, Short Blade, Marksman",
    "sign": "The Thief"
  },
  {
    "cat": "Ynesai",
    "name": "Ynesai male — Athletics and Unarmored",
    "race": "Ynesai",
    "gender": "Male",
    "spec": "Stealth",
    "fav": "Speed, Strength",
    "maj": "Athletics, Unarmored, Short Blade, Acrobatics, Sneak",
    "min": "Illusion, Marksman, Security, Light Armor, Speechcraft",
    "sign": "The Thief"
  },
  {
    "cat": "Ynesai",
    "name": "Ynesai female — Athletics and Unarmored",
    "race": "Ynesai",
    "gender": "Female",
    "spec": "Stealth",
    "fav": "Speed, Strength",
    "maj": "Athletics, Unarmored, Short Blade, Acrobatics, Sneak",
    "min": "Illusion, Marksman, Security, Light Armor, Speechcraft",
    "sign": "The Thief"
  },
  {
    "cat": "Duadri",
    "name": "Duadri male — Mysticism and Acrobatics",
    "race": "Duadri",
    "gender": "Male",
    "spec": "Stealth",
    "fav": "Willpower, Strength",
    "maj": "Mysticism, Acrobatics, Spear, Security, Sneak",
    "min": "Athletics, Unarmored, Light Armor, Mercantile, Short Blade",
    "sign": "The Thief"
  },
  {
    "cat": "Duadri",
    "name": "Duadri female — Mysticism and Acrobatics",
    "race": "Duadri",
    "gender": "Female",
    "spec": "Stealth",
    "fav": "Willpower, Strength",
    "maj": "Mysticism, Acrobatics, Spear, Security, Sneak",
    "min": "Athletics, Unarmored, Light Armor, Mercantile, Short Blade",
    "sign": "The Thief"
  }
];
